CREATE TABLE ESTATUS (
  IN_ID_ESTATUS int(11) NOT NULL,
  ST_ESTATUS varchar(45) DEFAULT NULL,
  PRIMARY KEY (IN_ID_ESTATUS)
);




CREATE TABLE NIVEL (
  IN_ID_NIVEL int(11) NOT NULL,
  ST_DESCRIPCION varchar(45) DEFAULT NULL,
  PRIMARY KEY (IN_ID_NIVEL)
);


CREATE TABLE TEMAS (
  IN_ID_TEMA int(11) NOT NULL,
  ST_NOMBRE varchar(45) DEFAULT NULL,
  ST_DESCRIPCION varchar(255) DEFAULT NULL,
  IN_ID_NIVEL int(11) DEFAULT NULL,
  PRIMARY KEY (IN_ID_TEMA),
  CONSTRAINT IN_ID_NIVEL FOREIGN KEY (IN_ID_NIVEL) REFERENCES nivel (IN_ID_NIVEL)
);



CREATE TABLE PREGUNTAS (
  IN_ID_PREGUNTAS int(11) NOT NULL,
  ST_NOMBRE varchar(255) DEFAULT NULL,
  ST_PREGUNTA longtext,
  IN_ID_NIVEL int(11) DEFAULT NULL,
  IN_ID_TEMA int(11) DEFAULT NULL,
  PRIMARY KEY (IN_ID_PREGUNTAS),
  CONSTRAINT IN_ID_TEMA FOREIGN KEY (IN_ID_TEMA) REFERENCES temas (IN_ID_TEMA),
  CONSTRAINT NIVEL FOREIGN KEY (IN_ID_NIVEL) REFERENCES nivel (IN_ID_NIVEL)
);

CREATE TABLE PISTAS (
  IN_ID_PISTAS int(11) NOT NULL,
  ST_PISTA varchar(45) DEFAULT NULL,
  IN_PREGUNTA int(11) DEFAULT NULL,
  IN_PREGUNTAS int(11) DEFAULT NULL,
  IN_ID_PREGUNTAS int(11) DEFAULT NULL,
  PRIMARY KEY (IN_ID_PISTAS),  
  CONSTRAINT PREGUNTA FOREIGN KEY (IN_PREGUNTA) REFERENCES preguntas (IN_ID_PREGUNTAS)
);




CREATE TABLE USUARIOS (
  IN_ID_USUARIO int(11) NOT NULL,
  ST_NOMBRE varchar(45) DEFAULT NULL,
  ST_APELLIDO_M varchar(45) DEFAULT NULL,
  ST_APELLIDO_P varchar(45) DEFAULT NULL,
  ST_USUARIO varchar(45) DEFAULT NULL,
  ST_CORREO varchar(45) DEFAULT NULL,
  ST_PASSWORD varchar(45) DEFAULT NULL,
  NIVELES_USUARIO_IN_ID_NIVELES varchar(45) DEFAULT NULL,
  PRIMARY KEY (IN_ID_USUARIO)
);




CREATE TABLE RESPONDIDAS (
  IN_RESPONDIDAS int(11) NOT NULL,
  IN_ID_ESTATUS int(11) DEFAULT NULL,
  IN_ID_USUARIO int(11) DEFAULT NULL,
  ST_ESTADO_REGISTRO varchar(45) DEFAULT NULL,
  IN_ID_TEMA int(11) DEFAULT NULL,
  ID_PREGUNTAS int(11) DEFAULT NULL,
  PRIMARY KEY (IN_RESPONDIDAS),
  CONSTRAINT IN_ID_ESTATUS FOREIGN KEY (IN_ID_ESTATUS) REFERENCES estatus (IN_ID_ESTATUS),
  CONSTRAINT IN_ID_PREGUNTAS FOREIGN KEY (ID_PREGUNTAS) REFERENCES preguntas (IN_ID_PREGUNTAS),
  CONSTRAINT TEMA FOREIGN KEY (IN_ID_TEMA) REFERENCES temas (IN_ID_TEMA),
  CONSTRAINT USUARIO FOREIGN KEY (IN_ID_USUARIO) REFERENCES usuarios (IN_ID_USUARIO)
);



CREATE TABLE RESPUESTAS (
  IN_ID_RESPUESTAS int(11) NOT NULL,
  ST_RESPUESTA varchar(45) DEFAULT NULL,
  IN_ID_PREGUNTA int(11) DEFAULT NULL,
  PRIMARY KEY (IN_ID_RESPUESTAS),
  CONSTRAINT IN_ID_PREGUNTA FOREIGN KEY (IN_ID_PREGUNTA) REFERENCES preguntas (IN_ID_PREGUNTAS)
);



CREATE TABLE EVALUACION (
  IN_ID_EVALUACION int(11) NOT NULL,
  ID_USUARIOS int(11) DEFAULT NULL,
  PRIMARY KEY (IN_ID_EVALUACION),
  CONSTRAINT USUARIOS FOREIGN KEY (ID_USUARIOS) REFERENCES usuarios (IN_ID_USUARIO)
);



INSERT INTO NIVEL
(IN_ID_NIVEL,
ST_DESCRIPCION)
VALUES
(1,
'BASICO');



INSERT INTO NIVEL
(IN_ID_NIVEL,
ST_DESCRIPCION)
VALUES
(2,
'INTERMEDIO');




INSERT INTO NIVEL
(IN_ID_NIVEL,
ST_DESCRIPCION)
VALUES
(3,
'AVANZADO');


INSERT INTO TEMAS
(IN_ID_TEMA,
ST_NOMBRE,
ST_DESCRIPCION,
IN_ID_NIVEL)
VALUES
(1,
'BASICO',
'PROGRAMACION ORIENTADA A OBJETOS',
1);



INSERT INTO USUARIOS
(IN_ID_USUARIO,
ST_NOMBRE,
ST_APELLIDO_M,
ST_APELLIDO_P,
ST_USUARIO,
ST_CORREO,
ST_PASSWORD,
NIVELES_USUARIO_IN_ID_NIVELES)
VALUES
(1,
'CESA RICARDO',
'RUIZ',
'ALDUCIN',
'OXCESARE',
'cesar180687@hotmail.com',
'123456789',
1);

INSERT INTO PREGUNTAS
(IN_ID_PREGUNTAS,
ST_NOMBRE,
ST_PREGUNTA,
IN_ID_NIVEL,
IN_ID_TEMA)
VALUES
(1,
'TOPICO 1',
' Consider the following program...  public class TestClass {     public int methodA(int a){  return a*2; } //1     public long methodA(int a){  returna; } //2     public static void main(String[] args)     {         int i = 0;         i = new TestClass().methodA(2);         System.out.println( i );     } } ',
1,
1);


INSERT INTO PREGUNTAS
(IN_ID_PREGUNTAS,
ST_NOMBRE,
ST_PREGUNTA,
IN_ID_NIVEL,
IN_ID_TEMA)
VALUES
(2,
'TOPICO 2',
'Given:  public class PlaceHolder<K, V> {     private K k;     private V v;     public PlaceHolder(K k, V v){         this.k = k;         this.v = v;     }     public K getK() { return k; }     public static <X> PlaceHolder<X, X> getDuplicateHolder(X x){         return new PlaceHolder<X, X>(x, x);     }     public static void main(String[] args) {       PlaceHolder<String, String> ph1 = PlaceHolder.getDuplicateHolder("b"); //1       PlaceHolder<String, String> ph2 = PlaceHolder<String>.getDuplicateHolder("b"); //2       PlaceHolder<String, String> ph3 = PlaceHolder<>.getDuplicateHolder("b"); //3       PlaceHolder<> ph4 = new PlaceHolder<String, String>("a", "b"); //4       PlaceHolder<?, ?> ph5 = new PlaceHolder(10, 10); //5            } } Which lines will fail compilation?',
1,
1);